
no_gpu: False
env: "nuplan"
output:
  location: "dagger_ccil/output"
  folder_suffix: ""
data:
  expert: None
  pkl: 'data/hopper-expert-v2_25.pkl'
  num_traj: '...'
  horizon: '...'
  num_datapoints: '...'
dynamics:
  lipschitz_type: "soft_sampling"
  lipschitz_constraint: 2.0
  soft_lipschitz_penalty_weight: 0.0005
  soft_lipschitz_sampling_eps: 0.0003
  soft_lipschitz_n_samples: 5
  lr: 0.001
  weight_decay: 0.00001
  layers: [512, 512]
  activation: relu
  train_epochs: 200
  batch_size: 1
  val_percentage: 1

  input_dim: 7
  output_dim: 7
  horizon: 20
  n_con_steps: 80
  cond_dim: 256
  map_cond: True
  n_cond_layers: 2
  
aug:
  type: 'backward_euler'
  max_iter: 50
  num_labels: 20
  delta: 0.00001
  epsilon:  10.0
  use_expert_label: False
policy:
  naive: False
  noise_bc: 0.0
  lr: 0.001
  batch_size: 64
  train_epochs: 200
eval:
  noise: [0.01]

